export const styles = {
    teamDataUnorderedList: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
        padding: '0',
        margin: '0',
        height: '100%',
        maxHeight: '100%',
        width: '100%',
        listStyleType: 'none',
        WebkitColumnCount: 2,
        MozColumnCount: 2,
        columnCount: 2,
        borderLeft: 'solid 1px var(--theme-orange)',
        borderRight: 'solid 1px var(--theme-orange)',
        overflow: 'auto'
    },
    teamDataUnorderedListsItems: {
        margin: '8px',
        height: '100%',
    },
    teamSelectedContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        height: '100%',
        width: '100%',
        position: 'absolute',
        backgroundColor: 'var(--theme-blue)',
        borderLeft: 'solid 1px var(--theme-orange)',
        borderRight: 'solid 1px var(--theme-orange)',
        zIndex: '100',
    },
    teamSelectedTypography: {
        mt: '32px',
        fontSize: '1.5em',
    },
    teamSelectedInnerContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        height: '64px',
        mt: '32px',
        pl: '16px',
        border: '1px solid var(--theme-orange)',
        overflow: 'auto',
        padding: '0',
        overflowX: 'auto',
        overflowY: 'hidden',
    },
    // backgroundCover: {
    //     position: 'absolute',
    //     height: '64px',
    //     backgroundColor: 'var(--theme-white)',
    // },
    weeklyScheduleNavigationButton: {
        color: 'var(--theme-orange)',
    },
}