export const styles = {
    teamDataUnorderedList: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
        padding: '0',
        margin: '0',
        height: '100%',
        maxHeight: '100%',
        width: '100%',
        listStyleType: 'none',
        WebkitColumnCount: 2,
        MozColumnCount: 2,
        columnCount: 2,
        borderLeft: 'solid 1px var(--theme-orange)',
        borderRight: 'solid 1px var(--theme-orange)',
        overflow: 'auto'
    },
    teamDataUnorderedListsItems: {
        margin: '8px',
        height: '100%',
    },
    teamSelectedContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        height: '100%',
        width: '100%',
        position: 'absolute',
        backgroundColor: 'var(--theme-blue)',
        borderLeft: 'solid 1px var(--theme-orange)',
        borderRight: 'solid 1px var(--theme-orange)',
        zIndex: '100',
    },
    teamSelectedTypography: {
        marginTop: '32px',
        fontSize: '1.5em',
    },
    teamSelectedInnerContainer: {
        position: 'relative',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        height: '64px',
        marginTop: '32px',
        paddingLeft: '16px',
        border: '1px solid var(--theme-orange)',
        overflow: 'auto',
        padding: '0',
        overflowX: 'auto',
        overflowY: 'hidden',
        '& #firstWeek': {
            marginLeft: '8px !important',
        },
    },
    weeklyScheduleNavigationIcon: {
        color: 'var(--theme-orange)',
        zIndex: '999',
    },
    numberOfTheWeek: {
        display: 'flex',
        flexShrink: '0',
        flexGrow: '0',
        paddingX: '8px',
    }
}