export const fakeTeams = [
    'Philadelphia Eagles',
    'Phillies',
    '76ers',
    'Union',
    'Flyers',
    'Norristown Bandits',
    'New York Yankees',
    'Los Angeles Lakers',
    'Dallas Cowboys',
    'Boston Red Sox',
    'Chicago Bulls',
    'Green Bay Packers',
    'Golden State Warriors',
    'Pittsburgh Steelers',
    'San Francisco Giants',
    'New England Patriots'
];

export const fakeNotifications = [
    'John Doe',
    'Chief Keef',
    'Pex Ranger',
    'Sally',
    'Jeff100',
    'xrel12',
    '1234Hey',
    'iloveFootball',
    'Eaglesrule',
    'SuperCoder123',
    'TechExplorer24',
    'StarGazer99',
    'PexRanger16',
    'AdventureSeeker77',
    'MusicMaestro55',
    'FitnessFanatic19',
    'TravelEnthusiast7',
    'FoodieDelight',
    'GamingNinja21',
    'MovieBuff123'
];
